name:               telescope-example
version:            0.4.0
synopsis:           Example for Telescope
github:             dkistdc/telescope.hs
license:            BSD-3-Clause
author:             Sean Hess
maintainer:         shess@nso.edu
copyright:          (c) 2024 Sean Hess
category:           Science, Astronomy

language: GHC2021

ghc-options:
  - -Wall
  - -fdefer-typed-holes

default-extensions:
  - OverloadedStrings

dependencies:
  - base
  - text
  - bytestring
  - telescope
  - filepath
  - Chart
  - Chart-diagrams
  - effectful
  - string-interpolate
  - massiv
  - massiv-io
  - JuicyPixels
  - Color == 0.4.0


executables:
  example:
    main:                Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    source-dirs:
      - ./app
    dependencies: []
