name:                telescope
version:             0.4.0
synopsis:            Astronomical Observations (FITS, ASDF, WCS, etc)
description:         Work with astronomical observations from modern telescopes
homepage:            https://github.com/dkistdc/telescope.hs
license:             BSD3
author:              Sean Hess
maintainer:          Sean Hess <shess@nso.edu>
copyright:           (c) 2024 Sean Hess
category:            Science, Astronomy
extra-source-files:
  - README.md
  - src/checksum.c
  - src/checksum.h

language: GHC2021

ghc-options:
  - -Wall
  - -fdefer-typed-holes

default-extensions:
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DerivingStrategies
  - DuplicateRecordFields
  - LambdaCase
  - NoFieldSelectors
  - OverloadedRecordDot
  - OverloadedStrings
  - QuasiQuotes
  - StrictData
  - TypeApplications
  - TypeFamilies

dependencies:
  - base >=4.18 && <5
  - binary >= 0.8.9 && <0.9
  - bytestring >= 0.11 && <0.13
  - exceptions >= 0.10 && <0.11
  - massiv >= 1.0 && < 1.1
  - massiv-io >= 1.0 && < 1.1
  - megaparsec >= 9.6 && <9.7
  - text >= 2.0 && <3
  - effectful >= 2.3 && <3
  - time >= 1.12 && < 2
  - scientific >= 0.3 && < 0.4
  - byte-order >= 0.1.3 && < 0.2
  - casing >= 0.1.4 && < 0.2
  - libyaml >= 0.1.4 && < 0.2
  - conduit >= 1.3 && < 1.4
  - resourcet-effectful >= 1.0.1 && < 1.1

library:
  source-dirs: src
  other-modules:
    - Paths_telescope
  c-sources:
    - src/checksum.c


tests:
  test:
    main: Spec.hs
    source-dirs: test/
    build-tools: skeletest:skeletest-preprocessor
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -F -pgmF=skeletest-preprocessor
    dependencies:
    - telescope
    - binary
    - containers
    - skeletest



